exec-once = awww-daemon
exec-once = sleep 0.5 && awww img ~/Wallpapers/FrierenBattleField.webp
exec-once = waybar
exec-once = mako
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets


exec = hyprctl setcursor default 30
