env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = GTK_THEME,adw-gtk3-dark
env = QT_QPA_PLATFORMTHEME, qt5ct
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/gcr/ssh
